# Generated by Django 5.2.7 on 2025-11-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
