# Generated by Django 5.2.7 on 2025-11-03 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0002_alter_customuser_options_remove_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(verbose_name="Дата оплаты")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                        default="transfer",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                ("course", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
                ("lesson", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="courses.lesson")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
