# Generated by Django 5.2.7 on 2025-11-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="course",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="lesson",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
            ),
        ),
    ]
