# Generated by Django 5.2.7 on 2025-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0004_alter_payments_course_alter_payments_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="lesson",
        ),
        migrations.AddField(
            model_name="payments",
            name="course",
            field=models.ManyToManyField(blank=True, null=True, to="courses.course"),
        ),
        migrations.AddField(
            model_name="payments",
            name="lesson",
            field=models.ManyToManyField(blank=True, null=True, to="courses.lesson"),
        ),
    ]
