# Generated by Django 5.2.7 on 2025-11-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payments_course_remove_payments_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"ordering": ["-payment_date"], "verbose_name": "оплата", "verbose_name_plural": "оплаты"},
        ),
    ]
