# Generated by Django 5.2.7 on 2025-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="id сессии платежа"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
