# Generated by Django 5.2.7 on 2025-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="ссылка на оплату"),
        ),
    ]
