# Generated by Django 5.2.7 on 2025-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payments_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Последний вход"),
        ),
    ]
