# Generated by Django 5.2.7 on 2025-10-31 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название курса")),
                ("description", models.CharField(max_length=300, verbose_name="Описание")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Иллюстрация")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название урока")),
                ("description", models.CharField(max_length=300, verbose_name="Описание")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Иллюстрация")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на YouTube, Vimeo или другое видео",
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Ссылка на видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["name"],
            },
        ),
    ]
