# Generated by Django 5.2.7 on 2025-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_course_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена"),
        ),
    ]
